apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-manager
  namespace: argocd
spec:
  project: ai-tools
  source:
    repoURL: https://github.com/AI-Technology-Apps/argocd-apps.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true