open-webui:
  ollama:
    enabled: false

  pipelines:
    # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
    enabled: false
  ingress:
    enabled: true
    class: "traefik"
    host: "chat.kjones.org" # update to your real domain
    tls: false

  persistence:
    enabled: true
    size: 5Gi

  # -- Node labels for pod assignment.
  nodeSelector:
    node-role.kubernetes.io/worker: pi-worker

  # -- Tolerations for pod assignment
  tolerations:
    - key: "node-role.kubernetes.io/worker"
      operator: "Equal"
      value: "pi-worker"
      effect: "NoSchedule"

  extraEnvVars:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-api-key
          key: api-key
