name: Generate ApplicationSet

on:
  push:
    paths:
      - 'apps/**/chart-config.yaml'
      - 'tools/generate_appset_list.py'
  workflow_dispatch:

jobs:
  build-appset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Generate ApplicationSet
      run: python tools/generate_appset_list.py

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git add manifests/generated-applicationset.yaml
          git commit -m "🔄 Auto-generate ApplicationSet"
          git push
        else
          echo "No changes to commit."
        fi